### PR TITLE
Fix init to not update

### PR DESCRIPTION
**Pull request by tpfau**
Correcting Tutorials to not automatically update the toolbox when run.
Ensuring that updates only happen when manually initializing the toolbox.

### CODE REVIEW

**Comment by laurentheirendt** [comment]
@tpfau, may you do a rebase after #47? Thanks.

**Comment by laurentheirendt** [comment]
This PR now needs rebasing.

**Comment by tpfau** [comment]
Should be done

**Comment by tpfau** [comment]
ok... something went VERY wrong here....

**Pull request closed without merging**
