### PR TITLE
Fix incorrect irreversible -> reversible

### PR DESCRIPTION
**Pull request by matthiaskoenig**

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Thanks @matthiaskoenig. May you actually only change the `.mlx` file and then generate the `.m` from there? Also, may you branch from `develop`? Thanks.

**Comment by matthiaskoenig** [comment]
Hi @laurentheirendt, 
sorry, but this seems to much trouble for fixing a typo. Feel free to fix this in the develop branch and close this pull request. 

Basically I would have to 
- organise a matlab license
- install matlab (and probably get the cobra toolbox running)
- figure out what mlx is and who to convert it to m in a way that is compatible with this repo
- open a new pull request.

Best M

**Comment by laurentheirendt** [comment]
Thanks for submitting the PR though, but unless the typo is fixed in the `.mlx` file, the typo will not be fixed in the `.m` file. Don't worry, I will take care of it.

**Comment by laurentheirendt** [comment]
Closing in favor of PR #55.

**Pull request closed without merging**
